### ISSUE TITLE
Andmebaasi liides pole isoleeritud Front End-st

### ISSUE THREAD

**Issue by ragnarkurm** [Murtpoiss/kool#1]
functions.php sisaldab sul salvestamise liidese funktsionaalsust, kuid see on samal ajal seotud Front End funktsionaalsusega. Näiteks $_POST, $_GET jne.

Mõned näited, kuidas peaks olema:
$entry = array( ... );
addnew($entry);
$entry = getone($id);
del($id);
update($entry);

Eesmärk oli andmete säilitamse kood täielikult eralda Front End-st ja Businesst Logic-st.

**Comment by Murtpoiss** [comment]
done

**Comment by ragnarkurm** [comment]
Näen ikka veel functions.php failis $_POST asju ...
