### ISSUE TITLE
salvestamise API merge on puudu

### ISSUE THREAD

**Issue by ragnarkurm** [Murtpoiss/kool#2]

**Comment by Murtpoiss** [comment]
Liiga palju peame muutma oma muutujaid ja koodi et ei hakka seda tegema :D

**Comment by ragnarkurm** [comment]
Ma arvasin, et sul on suht hea kood...
Väljaspool API-t, on muudatused minimaalsed (põhiliselt funktsiooni nimi).
API sees - kui sul on hea kood, siis pole kellegil sinna midagi lisada või muuta...
Milleks vaja muutujaid mudida nii palju?
