### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by ragnarkurm** [Murtpoiss/kool#4]
Vaja teha.

Pane tähele, et iga probleem, mis leitakse su koodist tuleb teha eraldi issue, mitte 3 probleemi per 1 issue.

**Comment by Murtpoiss** [comment]
Saime parem kokku ja tegime nii muudatused sisse juba ja DONE

**Comment by ragnarkurm** [comment]
Sel juhul, kuidas seda trackida?
Kust ma tean, milline oli review ja mida sa sellega peale hakkasid?
Mille põhjal ma seda punkti hindan?

**Comment by ragnarkurm** [comment]
ootan, et siis tagantjärgi produtseerid vastavad issued ning seod vastava commitiga, et näeksin, kuidas neid asju lahendasid.
